AWSTemplateFormatVersion: 2010-09-09

Parameters:
    ParticipantTableName:
        Description: Name for dynamodb participant table.
        Type: String
        Default: hooked-participants

Resources:
    # Dynamodb
    DynamodbTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
            -   AttributeName: id
                AttributeType: S
            KeySchema:
            -   AttributeName: id
                KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            TableName: !Ref ParticipantTableName
